# Generated by Django 5.0.6 on 2025-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_categoria_alter_producto_categoria_movimientocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin_cliente', 'Administrador Cliente'), ('vendedor', 'Vendedor'), ('gerente', 'Gerente')], default='vendedor', max_length=20),
        ),
    ]
