# Generated by Django 6.0 on 2025-12-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_usuarioadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
    ]
