# Generated by Django 5.2.9 on 2025-12-03 05:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import gestion.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(validators=[gestion.utils.validar_precio_positivo])),
                ('fecha', models.DateTimeField(auto_now_add=True, validators=[gestion.utils.validar_fecha_no_futura])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido')], default='pendiente', max_length=20)),
                ('empresa_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.IntegerField(validators=[gestion.utils.validar_precio_positivo])),
                ('costo', models.IntegerField(validators=[gestion.utils.validar_precio_positivo])),
                ('categoria', models.CharField(max_length=100)),
                ('empresa_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=20, validators=[gestion.utils.validar_rut])),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, validators=[gestion.utils.validar_telefono_chileno])),
                ('email', models.EmailField(max_length=254)),
                ('empresa_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20, validators=[gestion.utils.validar_telefono_chileno])),
                ('empresa_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin_cliente', 'Administrador Cliente'), ('vendedor', 'Vendedor'), ('gerente', 'Gerente')], default='vendedor', max_length=20)),
                ('empresa_id', models.IntegerField(blank=True, help_text='ID empresa master. Null si es Superuser', null=True)),
                ('rut', models.CharField(blank=True, max_length=20, validators=[gestion.utils.validar_rut])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[gestion.utils.validar_cantidad_item])),
                ('costo_unitario', models.IntegerField(validators=[gestion.utils.validar_precio_positivo])),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.proveedor'),
        ),
        migrations.CreateModel(
            name='PedidoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(validators=[gestion.utils.validar_precio_positivo])),
                ('estado', models.CharField(default='solicitado', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True, validators=[gestion.utils.validar_fecha_no_futura])),
                ('empresa_id', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra)'), ('salida', 'Salida (Venta)'), ('ajuste', 'Ajuste Manual'), ('merma', 'Merma/Pérdida')], max_length=20)),
                ('cantidad', models.IntegerField(validators=[gestion.utils.validar_cantidad_item])),
                ('fecha', models.DateTimeField(auto_now_add=True, validators=[gestion.utils.validar_fecha_no_futura])),
                ('referencia', models.CharField(help_text='ID de Venta #100 o Compra #50', max_length=100)),
                ('empresa_id', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('punto_reorden', models.IntegerField(default=5)),
                ('empresa_id', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.sucursal'),
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.IntegerField(validators=[gestion.utils.validar_precio_positivo])),
                ('monto_final', models.IntegerField(null=True, validators=[gestion.utils.validar_precio_positivo])),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, validators=[gestion.utils.validar_fecha_no_futura])),
                ('fecha_cierre', models.DateTimeField(null=True, validators=[gestion.utils.validar_fecha_no_futura])),
                ('empresa_id', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(validators=[gestion.utils.validar_precio_positivo])),
                ('metodo_pago', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True, validators=[gestion.utils.validar_fecha_no_futura])),
                ('empresa_id', models.IntegerField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[gestion.utils.validar_cantidad_item])),
                ('precio_unitario', models.IntegerField(validators=[gestion.utils.validar_precio_positivo])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.venta')),
            ],
        ),
    ]
