# Generated by Django 5.2.9 on 2025-12-03 08:17

import django.db.models.deletion
import django.utils.timezone
import empresas.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=20, unique=True, validators=[empresas.utils.validar_rut])),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[empresas.utils.validar_telefono_chileno])),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('db_host', models.CharField(blank=True, help_text='Ej: ec2-basico o IP', max_length=100, null=True)),
                ('db_name', models.CharField(blank=True, max_length=100, null=True)),
                ('db_user', models.CharField(blank=True, max_length=100, null=True)),
                ('db_password', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('basico', 'Plan Básico'), ('estandar', 'Plan Estándar'), ('premium', 'Plan Premium')], max_length=50, unique=True)),
                ('precio_mensual', models.IntegerField(validators=[empresas.utils.validar_precio_positivo])),
                ('max_sucursales', models.IntegerField()),
                ('max_usuarios', models.IntegerField()),
                ('modulos_json', models.JSONField(default=dict)),
                ('host_base_url', models.URLField(default='http://localhost:8001/api/basico', help_text='URL de la API para este plan')),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(validators=[empresas.utils.validar_precio_positivo])),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pagado', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ec2_instance', models.CharField(blank=True, help_text='Ej: ec2-basico', max_length=50, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.plan')),
            ],
        ),
    ]
